export const ghanaConfig = {
  key: 'gh',
  flag: '🇬🇭',
  label: 'Ghana',
  orgName: 'BeaconPath Ghana',
  fullOrgName: 'Beacon of New Beginnings',
  tagline: 'Healing hope for survivors in Ghana',
  heroAlt: 'Survivors supported by Beacon in Ghana',
  serviceArea: 'Greater Accra',
  country: 'Ghana',
  address: 'Accra, Ghana',
  phone1: '+233 55 171 0100',
  phone2: '+233 55 348 9806',
  email: 'info@beaconnewbeginnings.org',
  emergencyHotline: '0800 800 800',
  emergencyHotlineLabel: 'DOVVSU DV Hotline (free)',
  emergencyServices: '191',
  dvAuthority: 'DOVVSU',
  defaultCurrency: 'GHS',
  footerResources: [
    { label: 'DOVVSU', href: 'https://police.gov.gh' },
    { label: 'WiLDAF Ghana', href: 'https://wildafghana.org' },
    { label: 'Legal Aid Board', href: 'https://legalaid.gov.gh' },
    { label: 'Emergency: 191 / 193', href: 'tel:191' },
  ],
};

export const usConfig = {
  key: 'us',
  flag: '🇺🇸',
  label: 'United States',
  orgName: 'Beacon of New Beginnings',
  fullOrgName: 'Beacon of New Beginnings',
  tagline: 'Healing hope for survivors across the US',
  heroAlt: 'Survivors supported by Beacon of New Beginnings',
  serviceArea: 'Nationwide',
  country: 'United States',
  address: 'Online / Remote',
  phone1: '+1 (614) 377-6633',
  phone2: '',
  email: 'info@beaconnewbeginnings.org',
  emergencyHotline: '1-800-799-7233',
  emergencyHotlineLabel: 'National DV Hotline (free, 24/7)',
  emergencyServices: '911',
  dvAuthority: 'National DV Hotline',
  defaultCurrency: 'USD',
  footerResources: [
    { label: 'National DV Hotline', href: 'https://thehotline.org' },
    { label: 'RAINN', href: 'https://rainn.org' },
    { label: 'Crisis Text Line', href: 'sms:741741' },
    { label: 'Emergency: 911', href: 'tel:911' },
  ],
};

export const allConfigs = { gh: ghanaConfig, us: usConfig };
